[package]
name = "wanaplay-booker"
version = "0.1.0"
authors = ["Nicolas Berard <berard.nicolas@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { path = "../reqwest" }
env_logger = "0.5"
rust-crypto = "0.2.36"
structopt = "0.2"
chrono = "0.4.0"
select = "0.4.2"
scraper = "0.9.0"